### ISSUE TITLE
Add additional meta tags (for SEO)

### ISSUE THREAD

**Issue by Flamov** [Flamov/steamchat-website#20]
**References:**
- https://github.com/joshbuchea/HEAD
- https://github.com/marcobiedermann/search-engine-optimization

**Currently missing:**

- [_Meta_](https://github.com/joshbuchea/HEAD#meta)
  - [x] `<meta http-equiv="x-ua-compatible" content="ie=edge">`
  - [x] `<meta name="subject" content="your website's subject">`
- [_Link_](https://github.com/joshbuchea/HEAD#link)
  - [x] `<link rel="archives" href="https://example.com/archives/">`
  - [x] `<link rel="index" href="https://example.com/">`
  - [x] `<link rel="first" href="https://example.com/atomFeed.php">`
  - [x] `<link rel="next" href="https://example.com/atomFeed.php?page=4">`
  - [x] `<link rel="prev" href="https://example.com/atomFeed.php?page=2">`
  - [x] `<link rel="last" href="https://example.com/atomFeed.php?page=147">`
  - [x] `<link rel="alternate" href="https://feeds.feedburner.com/example" type="application/rss+xml" title="RSS">`
- [x] [_Favicons_](https://github.com/joshbuchea/HEAD#favicons)
- [x] [_Twitter Cards_](https://github.com/joshbuchea/HEAD#twitter-cards)
- [_Apple iOS_](https://github.com/joshbuchea/HEAD#apple-ios)
  - [x] `<link rel="apple-touch-icon" href="/path/to/apple-touch-icon.png">`
- [_Apple Safari_](https://github.com/joshbuchea/HEAD#apple-safari)
  - [x] `<link rel="mask-icon" href="/path/to/icon.svg" color="red">`
- [x] [_Google Android_](https://github.com/joshbuchea/HEAD#google-android)
  - [x] `<meta name="theme-color" content="#E64545">`
- [x] [_Microsoft Internet Explorer_](https://github.com/joshbuchea/HEAD#microsoft-internet-explorer)

**SEO Images:**
* [http://www.favicomatic.com/](http://www.favicomatic.com/)

**After deployment:**
- [_Meta_](https://github.com/joshbuchea/HEAD#meta)
  - [ ] `<meta name="google-site-verification" content="verification_token">`
  - [ ] `<meta name="msvalidate.01" content="verification_token">`
